import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { MayaControls } from './MayaControls'

afterEach(() => vi.unstubAllGlobals())
const capabilities = ['orbis-maya:development:development.deploy', 'orbis-maya:development:audit.read']
const client = () => ({ token: vi.fn().mockResolvedValue('session-token'), login: vi.fn().mockResolvedValue(undefined), logout: vi.fn().mockResolvedValue(undefined), dispose: vi.fn() })
const revision = 'a'.repeat(40)
describe('Maya owner controls', () => {
  it('keeps controls disabled when login is unconfigured', async () => {
    render(<MayaControls load={async () => null} />)
    await screen.findByText('Owner login এখনো configure করা হয়নি।')
    expect(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' })).toBeDisabled()
    expect(screen.queryByRole('button', { name: 'Google দিয়ে owner login' })).toBeNull()
    expect(screen.getByText(/Public release বন্ধ/)).toBeTruthy()
  })
  it('allows Google login without treating a local session as permission', async () => {
    const auth = client(); auth.token.mockResolvedValue(null)
    render(<MayaControls load={async () => auth} />)
    await screen.findByText('Controls ব্যবহার করতে owner login করুন।')
    fireEvent.click(screen.getByRole('button', { name: 'Google দিয়ে owner login' }))
    await waitFor(() => expect(auth.login).toHaveBeenCalled())
    expect(screen.getByRole('button', { name: 'Audit দেখুন' })).toBeDisabled()
  })
  it('requires server-verified capabilities, confirms an exact revision and shows accepted versus live', async () => {
    const auth = client()
    const fetcher = vi.fn().mockResolvedValueOnce(Response.json({ capabilities }))
      .mockResolvedValueOnce(Response.json({ confirmation: 'c'.repeat(64), actionId: 'action' }))
      .mockResolvedValueOnce(Response.json({ state: 'accepted', actionId: 'action', deployId: 'dep-accepted' }))
      .mockResolvedValueOnce(Response.json([{ action_id: 'action', state: 'accepted' }]))
    vi.stubGlobal('fetch', fetcher)
    render(<MayaControls load={async () => auth} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    fireEvent.change(screen.getByLabelText('যাচাই করা Maya main commit SHA'), { target: { value: revision } })
    fireEvent.click(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' }))
    await screen.findByRole('button', { name: 'এই development deploy নিশ্চিত করুন' })
    expect(fetcher).toHaveBeenCalledTimes(2)
    fireEvent.click(screen.getByRole('button', { name: 'এই development deploy নিশ্চিত করুন' }))
    await screen.findByText(/LIVE status আলাদা করে যাচাই/)
    expect(fetcher.mock.calls[2][1]).toMatchObject({ headers: { authorization: 'Bearer session-token' } })
    fireEvent.click(screen.getByRole('button', { name: 'Audit দেখুন' }))
    expect(await screen.findByLabelText('Maya action audit')).toHaveTextContent('accepted')
    fireEvent.click(screen.getByRole('button', { name: 'Logout' }))
    await screen.findByText('Owner session বন্ধ হয়েছে।')
    expect(screen.queryByLabelText('Maya action audit')).toBeNull()
    expect(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' })).toBeDisabled()
  })
  it('cancels confirmation when revision changes or owner cancels', async () => {
    const auth = client()
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ capabilities }))
      .mockImplementation(async () => Response.json({ confirmation: 'c'.repeat(64), actionId: 'action' })))
    render(<MayaControls load={async () => auth} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    const input = screen.getByLabelText('যাচাই করা Maya main commit SHA')
    fireEvent.change(input, { target: { value: revision } })
    fireEvent.click(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' }))
    await screen.findByRole('button', { name: 'বাতিল করুন' })
    fireEvent.click(screen.getByRole('button', { name: 'বাতিল করুন' }))
    expect(screen.queryByRole('button', { name: 'এই development deploy নিশ্চিত করুন' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' }))
    await screen.findByRole('button', { name: 'বাতিল করুন' })
    fireEvent.change(input, { target: { value: 'b'.repeat(40) } })
    expect(screen.queryByRole('button', { name: 'এই development deploy নিশ্চিত করুন' })).toBeNull()
  })
  it.each([null, {}, { capabilities: 1 }, { capabilities: [1] }])('rejects malformed owner permission response %j', async (owner) => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json(owner)))
    render(<MayaControls load={async () => client()} />)
    await screen.findByText('Owner login বা permission যাচাই হয়নি। আবার চেষ্টা করুন।')
    expect(screen.getByRole('button', { name: 'Audit দেখুন' })).toBeDisabled()
  })
  it('preserves a safe UI when login initialization fails', async () => {
    render(<MayaControls load={async () => { throw new Error('secret') }} />)
    await screen.findByText('Owner login বা permission যাচাই হয়নি। আবার চেষ্টা করুন।')
    expect(screen.queryByText('secret')).toBeNull()
  })
  it.each([null, 'bad', {}, { confirmation: 'x' }, { confirmation: 1, actionId: 'x' }, { confirmation: 'x', actionId: 1 }])('rejects malformed preparation %j', async (prepared) => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ capabilities })).mockResolvedValueOnce(Response.json(prepared)))
    render(<MayaControls load={async () => client()} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    fireEvent.change(screen.getByLabelText('যাচাই করা Maya main commit SHA'), { target: { value: revision } })
    fireEvent.click(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' }))
    await screen.findByText(/কাজ নিশ্চিত হয়নি/)
    expect(screen.queryByRole('button', { name: 'এই development deploy নিশ্চিত করুন' })).toBeNull()
  })
  it.each(['expired', 'failed'])('handles request-time session or server failure %s', async (reason) => {
    const auth = client()
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ capabilities })).mockResolvedValueOnce(new Response('', { status: 503 })))
    render(<MayaControls load={async () => auth} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    if (reason === 'expired') auth.token.mockResolvedValue(null)
    fireEvent.click(screen.getByRole('button', { name: 'Audit দেখুন' }))
    await screen.findByText(/কাজ নিশ্চিত হয়নি/)
  })
  it('disposes authentication when initialization completes after unmount', async () => {
    const auth = client(); let finish!: (value: typeof auth) => void
    const pending = new Promise<typeof auth>((resolve) => { finish = resolve })
    const view = render(<MayaControls load={() => pending} />); view.unmount()
    await act(async () => { finish(auth); await pending })
    expect(auth.dispose).toHaveBeenCalled()
  })
  it('disposes an initialized authentication client on unmount', async () => {
    const auth = client(); auth.token.mockResolvedValue(null)
    const view = render(<MayaControls load={async () => auth} />)
    await screen.findByText('Controls ব্যবহার করতে owner login করুন।')
    view.unmount(); expect(auth.dispose).toHaveBeenCalled()
  })
  it.each([null, 'bad', {}, { state: 'wrong' }, { state: 'accepted' }, { state: 'accepted', actionId: 'wrong' },
    { state: 'accepted', actionId: 'action' }, { state: 'accepted', actionId: 'action', deployId: 4 },
    { state: 'accepted', actionId: 'action', deployId: 'wrong' }])('does not claim deploy acceptance for malformed acknowledgement %j', async (result) => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ capabilities }))
      .mockResolvedValueOnce(Response.json({ confirmation: 'c'.repeat(64), actionId: 'action' }))
      .mockResolvedValueOnce(Response.json(result)))
    render(<MayaControls load={async () => client()} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    fireEvent.change(screen.getByLabelText('যাচাই করা Maya main commit SHA'), { target: { value: revision } })
    fireEvent.click(screen.getByRole('button', { name: 'Development deploy প্রস্তুত করুন' }))
    fireEvent.click(await screen.findByRole('button', { name: 'এই development deploy নিশ্চিত করুন' }))
    await screen.findByText(/কাজ নিশ্চিত হয়নি/)
    expect(screen.queryByText(/Deploy request গ্রহণ/)).toBeNull()
  })
  it('rejects malformed audit responses', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ capabilities })).mockResolvedValueOnce(Response.json({})))
    render(<MayaControls load={async () => client()} />)
    await screen.findByText('Owner session যাচাই হয়েছে।')
    fireEvent.click(screen.getByRole('button', { name: 'Audit দেখুন' }))
    await screen.findByText(/কাজ নিশ্চিত হয়নি/)
  })
  it('ignores a failed login initializer after unmount', async () => {
    let reject!: (error: Error) => void
    const pending = new Promise<null>((_resolve, fail) => { reject = fail })
    const view = render(<MayaControls load={() => pending} />); view.unmount()
    await act(async () => { reject(new Error('offline')); await pending.catch(() => undefined) })
  })
  it('ignores a pending server permission response after unmount', async () => {
    let finish!: (value: Response) => void
    const pending = new Promise<Response>((resolve) => { finish = resolve })
    const fetcher = vi.fn().mockReturnValue(pending); vi.stubGlobal('fetch', fetcher)
    const view = render(<MayaControls load={async () => client()} />)
    await waitFor(() => expect(fetcher).toHaveBeenCalled()); view.unmount()
    await act(async () => { finish(Response.json({ capabilities })); await pending })
  })
})
